
# Tested on (GPUs, CUDA, Driver): tag
# (L4, 12.2, 535): 23.10-py3
FROM nvcr.io/nvidia/pytorch:23.10-py3 AS base

# Go to workspace
WORKDIR /workspace

RUN bash -c "pip install tensordict torchrl opencv-fixer==0.2.5" 

# WORKDIR /workspace/
